- name: configure user 
  hosts: user
  become: yes
  tasks: 
  - name: disable default nodejs
    ansbile.builtin.command: "dnf module disable nodejs -y"

  - name: enable nodejs-20
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: install nodejs
    ansbile.builtin.dnf:
      name: nodejs
      state: installed

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory

  - name: add roboshop user 
    ansible.builtin.user:
      name: Roboshop 
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download user code
    ansible.builtin.get_url:
      src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: unzip user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
    
  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes 